env:
    global:
        - COVERALLS_REPO_TOKEN=eVqEedQyCAyqps3JPEt4DsCbSRcKEurdss
        
sudo: required

language: java

jdk:
  - oraclejdk8

before_script:
  - chmod +x gradlew
  
script:
  - ./gradlew check

after_success:
    fi
  - ./gradlew jacocoTestReport coveralls
