env:
    global:
        - CI_NAME:travis-pro
        - COVERALLS_REPO_TOKEN=eVqEedQyCAyqps3JPEt4DsCbSRcKEurdss
        
sudo: required

language: java

jdk:
  - oraclejdk8


before_script:
  - chmod +x gradlew
  
script:
  - ./gradlew check 

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_TEST_RESULT" == 0 ]; then 
  - ./gradlew jacocoTestReport coveralls
